```java
throw new Exception();
```
Exception을 발생시킨다. 해당 예외는 블록을 타고 catch문에 도달한다.