예외가 발생했을 때 throws로 지목한 예외 클래스를 참조한다.